apiVersion: v1
kind: Service
metadata:
  name: {{ include "room-presence.fullname" . }}
  labels:
    {{- include "room-presence.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "room-presence.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
